"""add Course field

Revision ID: 3c9cce53abfd
Revises: 8165047ba6ab
Create Date: 2024-03-31 23:13:46.179581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9cce53abfd'
down_revision: Union[str, None] = '8165047ba6ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('course', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'course')
    # ### end Alembic commands ###
