"""Add default rule for aboutm

Revision ID: 8165047ba6ab
Revises: c2c82d47171c
Create Date: 2024-03-24 23:11:13.684757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8165047ba6ab'
down_revision: Union[str, None] = 'c2c82d47171c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
